Added changes related to workflpow

diff --git a/.github/workflows/webapp-action.yml b/.github/workflows/webapp-action.yml
--- a/.github/workflows/webapp-action.yml
+++ b/.github/workflows/webapp-action.yml
@@ -18,4 +18,25 @@ jobs:
       - run: npm --version 
       - run: npm install
       - run: npm test
+
+      - name: Install Packer
+        run: |
+          wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
+          unzip packer_1.7.3_linux_amd64.zip
+          sudo mv packer /usr/local/bin/
+          packer version
+
+      - name : Zip the repo code
+        run: zip -r webapp.zip .
+        
+      - name: Init Packer
+        run: |
+          packer init ./aws-linux.pkr.hcl
+
+      - name: Validate Packer
+        run: |
+          if ! packer validate ./aws-linux.pkr.hcl; then
+              echo "Invalid AMI template. Please correct the errors and try again."
+              exit 1
+          fi
       
